### ISSUE TITLE
[BUG] iframe & image won't disappear when entering different room

### ISSUE THREAD

**Issue by ronnywang** [g0v/2d-online-chat#10]
1. Iframe from "chat2d" room
![image](https://user-images.githubusercontent.com/527063/82724174-d2c96500-9d06-11ea-9fc2-934a1c1c3ef8.png)

2. enter "ronnytest" room
![image](https://user-images.githubusercontent.com/527063/82724186-ea085280-9d06-11ea-80f2-6c74a12f8d90.png)

3. iframe from "chat2d" room is still here
![image](https://user-images.githubusercontent.com/527063/82724194-f5f41480-9d06-11ea-89a3-9bbdb373ccea.png)

**Comment by Stimim** [comment]
This should have been fixed by latest commit.
Can you verify and close the issue?

**Comment by ronnywang** [comment]
Yes, thank you~
