### ISSUE TITLE
[bug] sometimes walls are gone

### ISSUE THREAD

**Issue by ronnywang** [g0v/2d-online-chat#9]
![image](https://user-images.githubusercontent.com/527063/82724001-6b5ee580-9d05-11ea-86d2-7a6f07092963.png)

**Comment by Stimim** [comment]
- Do you know what are the steps to reproduce the issue?
- Or do you collect console logs when the issue happened?

**Comment by ronnywang** [comment]
I think that this bug has been fixed.. let me close this issue.
